name: CI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "master" branch
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        name: Build API
        runs-on: self-hosted

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - run: echo Start Build
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Install Node
              uses: actions/setup-node@v1
              with:
                    node-version: ${{ matrix.node-version}}
            - run: git pull origin master
            - run: npm i
            - run: npm install forever
            - run: npm run build
            - run: rm -rf /var/www/tranining/nestjs-api/*
            - run: mv /var/www/tranining/deploy-nestjs-api/actions-runner/_work/nestjs-api/nestjs-api/* /var/www/tranining/nestjs-api
            - run: forever start "npm start" ./
